image: adaptavist/all-tools:latest

definitions:
  tests: &test
    name: Tests
    script:
      - terraform fmt -check -recursive -diff
      - yarn install
      - (cd test/fixtures/default &&
        terraform init &&
        AWS_DEFAULT_REGION=us-east-1
        AWS_ACCESS_KEY_ID="${TF_TEST_AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY="${TF_TEST_AWS_SECRET_ACCESS_KEY}"
        terraform plan -out=plan.out &&
        terraform-compliance -f ./test -p plan.out)
    artifacts:
      - build/**

  release: &release
    name: Release

    caches:
      - node
    script:
      - yarn install
      - npx semantic-release -r ${BITBUCKET_GIT_HTTP_ORIGIN}
        # semantic release will perform S3 sync if successful

pipelines:
  default:
    - step: *test
  branches:
    master:
      - step: *test
      - step: *release
