#!/bin/sh

# disable in CI env
[ -n "$CI" ] && exit 0

. "$(dirname "$0")/_/husky.sh"
# excute commitizen cli prompt https://github.com/commitizen/cz-cli#optional-running-commitizen-on-git-commit
exec < /dev/tty && git cz --hook || true
exit 1 # Commit will be aborted

